package com.murphybob.spritepacker.converters;

import com.murphybob.spritepacker.ImagePacking;
import com.murphybob.spritepacker.NamedImage;
import org.apache.maven.plugin.MojoExecutionException;
import org.apache.maven.plugin.logging.Log;

import java.awt.Point;
import java.io.File;

/**
 * Converts ImagePacking to a CSS file, with the result that each icon gets its own class containing
 * background-position, width and height of the icon.
 *
 * @author mklein
 */
public class CssPackingConverter extends AbstractTextConverter {
    private final String cssPrefix;

    /**
     * Create a CSS converter with output file css and class prefix cssPrefix.
     *
     * @param css       the output CSS file to write to
     * @param cssPrefix the CSS class prefix for each icon class
     */
    public CssPackingConverter(File css, String cssPrefix) {
        super(css, "CSS");
        this.cssPrefix = cssPrefix;
    }

    /**
     * Create output CSS string based on an ImagePacking.
     *
     * @param imagePacking  the ImagePacking to convert
     * @param log           the log object to use
     * @return              String containing the CSS file contents
     * @throws MojoExecutionException
     */
    @Override
    protected String createOutput(ImagePacking imagePacking, Log log) throws MojoExecutionException {
        String prefix = (this.cssPrefix != "") ? this.cssPrefix+"-" : "";
        StringBuilder sb = new StringBuilder("/* this file is generated by the sprite packer. don't make any changes in here! */\n");
        for (NamedImage image : imagePacking.getImages()) {
            String name = image.getName();
            Point position = imagePacking.getPosition(image);
            String x = intToPixel(-position.x);
            String y = intToPixel(-position.y);
            String width = intToPixel(image.getWidth());
            String height = intToPixel(image.getHeight());
            sb.append(".").append(prefix).append(name).append("{background-position:").append(x).append(" ").append(y).append(";")
                    .append("width:").append(width).append(";height:").append(height).append(";}\n");
        }
        return sb.toString();
    }
}
